STATIC_UNIVERSITIES = []
STATIC_ENTRANCE_EXAMS = []
STATIC_LANGUAGE_EXAMS = []
STATIC_SCHOLARSHIPS = []
ALL_DEGREES = ["All", "Masters (M.Sc.)", "Masters (M.Tech/M.E.)", "MBA", "PhD", "Bachelors (B.Tech/B.E.)", "Bachelors (B.Sc.)"]
ALL_DOMAINS = ["All", "Engineering", "Computer Science", "Data Science & AI", "Management", "Medical & Health", "Law", "Sciences", "Design & Architecture", "Finance & Accounting"]
ALL_COUNTRIES = ["All", "India", "USA", "UK", "Canada", "Australia", "Germany", "Singapore", "Netherlands", "France", "Japan", "Argentina", "Brazil", "South Korea", "Italy", "Spain", "Ireland", "New Zealand", "Switzerland", "China", "Sweden", "Denmark", "Hong Kong", "Malaysia", "Norway", "Finland", "Austria", "Belgium", "Poland", "Portugal", "Czech Republic", "Mexico", "Chile", "Taiwan", "UAE", "Russia"]
ABROAD_COUNTRIES = [c for c in ALL_COUNTRIES if c not in ("All", "India")]
DEGREE_SHORT = {}
ROI_PROFILES = {}
LOAN_BANKS = {}
VISA_DATA = {"USA": {
"visa_type": "F-1 Student Visa",
"fee_inr": "₹13,800 (~$166)",
"sevis_fee": "$350",
"processing_weeks": "3–8 weeks",
"validity": "Duration of status (D/S)",
"work_rights": "20 hrs/week on-campus; OPT after graduation (12–36 months)",
"pr_path": "H-1B → Green Card (5–10+ years)",
"embassy_link": "https://in.usembassy.gov/visas/nonimmigrant-visas/student-visas/",
"documents": [
"I-20 from university (mandatory)",
"DS-160 form (online)",
"SEVIS fee receipt ($350)",
"Bank statements – 6 months (show full first-year costs)",
"Statement of Purpose",
"Official admission letter",
"Transcripts, test scores (GRE/GMAT, TOEFL/IELTS)",
"Passport (valid 6 months beyond stay)",
"Photo (2×2 inch, white background)",
"Financial sponsor's ITR (if parent-sponsored)",
],
"timeline": [
("Apply SEVIS & DS-160", "6 weeks before interview"),
("Schedule interview", "As early as possible (Jan slots in Jul)"),
("Visa interview", "4–8 weeks before program start"),
("Visa stamping", "1–7 days post-interview"),
("Travel", "30 days before program starts"),
],
"tips": [
"Book interview slot as early as possible — peak season (May–Aug) fills up 3 months ahead.",
"Demonstrate strong ties to India (family, property, job offer) to prove non-immigrant intent.",
"Carry all financial docs in original + copies. Prepare clear answers on your study plan.",
"SEVIS fee ($350) must be paid separately before the visa interview.",
],
},
"UK": {
"visa_type": "Student Visa (formerly Tier 4)",
"fee_inr": "₹37,000 (~£490 + IHS surcharge £776/yr)",
"sevis_fee": "N/A",
"processing_weeks": "3–4 weeks",
"validity": "Course duration + 4 months",
"work_rights": "20 hrs/week during term, full-time in holidays",
"pr_path": "Graduate Route (2-yr post-study) → Skilled Worker → ILR (5 yr)",
"embassy_link": "https://www.gov.uk/student-visa",
"documents": [
"CAS (Confirmation of Acceptance for Studies) from university",
"English proficiency: IELTS 6.0+ (most universities require 6.5)",
"Bank statements (28+ consecutive days, covering tuition + living ₹8L+ equivalent)",
"Official transcripts and degree certificates",
"Tuberculosis (TB) test from approved clinic (mandatory for India)",
"ATAS certificate (science/tech sensitive subjects)",
"Passport (valid for entire stay)",
"Parental consent (if under 18)",
],
"timeline": [
("Receive CAS from university", "4–6 weeks after conditional offer"),
("Apply for Student Visa online", "Up to 6 months before course start"),
("Biometrics appointment (VAC)", "Within 5 days of online application"),
("Visa decision", "Within 3–4 weeks"),
("Travel & BRP collection", "Within 10 days of arrival"),
],
"tips": [
"IHS (Immigration Health Surcharge) is ~£776/yr — budget this separately.",
"UK's Graduate Route allows 2 years of post-study work without a job offer.",
"28-day bank statement rule is strict — maintain balance for 28 consecutive days.",
"Apply for visa no earlier than 6 months before course start.",
],
},
"Canada": {
"visa_type": "Study Permit (SDS / Regular Stream)",
"fee_inr": "₹13,000 (~CAD $150)",
"sevis_fee": "GIC: CAD $10,200",
"processing_weeks": "4–8 weeks (SDS: ~20 days)",
"validity": "Course duration + 90 days",
"work_rights": "20 hrs/week off-campus; full-time during holidays",
"pr_path": "PGWP (up to 3 yr) → Express Entry / PNP → PR",
"embassy_link": "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html",
"documents": [
"Letter of Acceptance (LOA) from DLI",
"PAL (Provincial Attestation Letter) – new 2024 requirement",
"GIC (Guaranteed Investment Certificate) proof – CAD $10,200 with Scotiabank/CIBC",
"IELTS 6.0+ (SDS stream requires Academic IELTS 6.0)",
"Financial proof (tuition + 1st year living expenses)",
"Medical exam (IRCC-approved physician)",
"Passport (valid for full program)",
"Transcripts, test scores (GRE/GMAT if applicable)",
"Biometrics enrollment",
],
"timeline": [
("Apply for GIC + receive certificate", "1–2 weeks"),
("Submit online Study Permit application", "After receiving LOA + PAL"),
("Biometrics (if first time)", "Within 30 days of request"),
("Visa decision (SDS)", "~20 working days"),
("Port of Entry (PoE) letter → Study Permit at border", "Day of arrival"),
],
"tips": [
"SDS stream is faster (~20 days). Requires IELTS 6.0 and GIC — prioritise this.",
"PAL (Provincial Attestation Letter) is mandatory since Jan 2024. Request it early from province.",
"PGWP allows up to 3 years of work after graduation — Canada's strongest PR pathway for students.",
"Express Entry CRS score: Canadian education + work experience adds significant points.",
],
},
"Australia": {
"visa_type": "Student Visa (Subclass 500)",
"fee_inr": "₹29,500 (~AUD $620)",
"sevis_fee": "OSHC: ~AUD $600–900/yr",
"processing_weeks": "4–6 weeks",
"validity": "Course duration + 2 months",
"work_rights": "48 hrs/fortnight during term (post-Jul 2023)",
"pr_path": "Temporary Graduate (Subclass 485, 2–4 yr) → Skilled Migration → PR",
"embassy_link": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500",
"documents": [
"CoE (Confirmation of Enrolment) from institution",
"OSHC (Overseas Student Health Cover) for full study duration",
"English proof: IELTS 6.0+, PTE 50+, or TOEFL 64+",
"GTE (Genuine Temporary Entrant) statement",
"Financial evidence (tuition + living AUD $21,041/yr for 2024)",
"Passport + previous Australian visa history",
"Academic transcripts and certificates",
"Health examination (if required by DHA)",
],
"timeline": [
("Receive CoE + purchase OSHC", "After paying university deposit"),
("Online visa application (ImmiAccount)", "6–12 weeks before start"),
("Health and character checks", "During processing"),
("Visa grant letter received", "4–6 weeks"),
("Travel (must arrive before course start)", "On visa grant"),
],
"tips": [
"GTE statement is the most critical part — explain clearly why you intend to return to India.",
"Subclass 485 post-study work visa allows 2–4 years depending on study location (regional = longer).",
"Studying in regional Australia (outside Sydney/Melbourne) gives PR pathway bonuses.",
"Work rights: 48 hrs/fortnight during semester, unlimited during scheduled breaks.",
],
},
"Germany": {
"visa_type": "National Visa (D-type) for Study",
"fee_inr": "₹5,800 (~€75)",
"sevis_fee": "Blocked account: €11,208/yr",
"processing_weeks": "6–12 weeks",
"validity": "Course duration (renewable in-country)",
"work_rights": "120 full days or 240 half days per year",
"pr_path": "18-month job search visa → Blue Card → Permanent Residency (21 months with B1 German)",
"embassy_link": "https://india.diplo.de/in-en/service/visa-einreise/study/2238862",
"documents": [
"APS Certificate (Akademische Prüfstelle) – MANDATORY, takes 4–6 weeks",
"University admission letter (Zulassungsbescheid)",
"Blocked account (Sperrkonto) proof – €11,208 with Deutsche Bank, Expatrio, or Fintiba",
"Health insurance proof (public or private, minimum coverage)",
"Language proof: TestDaF TDN 4 / DSH-2 for German programs; IELTS/TOEFL for English programs",
"Transcripts + degree certificates (with apostille)",
"Passport (valid 6 months beyond intended stay)",
"Motivationsschreiben (motivation letter)",
"Biometric photos",
],
"timeline": [
("Apply for APS verification", "12–16 weeks before visa appointment"),
("Open blocked account (Sperrkonto)", "6–8 weeks before application"),
("Book visa appointment at German Consulate", "3–4 months ahead (slots very limited)"),
("Visa interview + document submission", "8–10 weeks before course start"),
("Visa decision", "4–8 weeks"),
("Arrive + register (Anmeldung) + convert to residence permit", "Within 90 days of arrival"),
],
"tips": [
"APS (Akademische Prüfstelle) verification is mandatory for Indian students — apply early, it takes 4–6 weeks and costs ~₹7,000.",
"Blocked account slots fill up — open with Expatrio or Fintiba immediately after admission.",
"German consulate appointment slots are extremely scarce — book months in advance.",
"German permanent residency can be obtained in as little as 21 months with B1 German proficiency.",
"Most Bachelor's/Master's programs at public universities are tuition-free (only ~€250–500 semester admin fee).",
],
},
"Singapore": {
"visa_type": "Student Pass (STP)",
"fee_inr": "₹2,500 (~SGD $30)",
"sevis_fee": "N/A",
"processing_weeks": "4–6 weeks",
"validity": "Course duration",
"work_rights": "16 hrs/week during semester; full-time during vacation",
"pr_path": "Employment Pass (EP) → Permanent Residence (2–3 years post-graduation, competitive)",
"embassy_link": "https://www.ica.gov.sg/pass-visa/student-pass",
"documents": [
"eForm 16 (issued by ICA via university's SOLAR+ system)",
"Official admission letter",
"Passport (valid 6+ months)",
"Financial proof (course fees + living expenses SGD $12,000+/yr)",
"Medical insurance",
"Passport-size photos",
"Academic transcripts and certificates",
],
"timeline": [
("University submits STP application via SOLAR+", "After enrollment confirmation"),
("ICA processes application", "4–6 weeks"),
("In-Principle Approval (IPA) letter received", "Before travel"),
("Arrive in Singapore + report to ICA", "Within 30 days of IPA"),
("Student Pass card issued", "Within 3–4 days"),
],
"tips": [
"Application is submitted by your university through the SOLAR+ system — you don't apply directly.",
"Very high approval rates for NUS, NTU, SMU students.",
"Singapore's EP pass is highly competitive — having a NUS/NTU degree significantly improves chances.",
"PR pathway is selective and based on economic contribution; plan for 3–5 years minimum.",
],
},
"Netherlands": {
"visa_type": "MVV (Machtiging tot Voorlopig Verblijf) + Residence Permit",
"fee_inr": "₹13,000 (~€192)",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks (via university IND sponsorship)",
"validity": "Course duration",
"work_rights": "16 hrs/week; full-time during summer",
"pr_path": "Zoekjaar (1-yr orientation visa) → HSM permit → Permanent Residence (5 yr)",
"embassy_link": "https://ind.nl/en/residence-permits/study",
"documents": [
"Admission letter from Dutch institution",
"University's IND sponsorship (processed by uni's international office)",
"Financial proof (€11,400+/yr)",
"Health insurance",
"Passport",
"Proof of accommodation in Netherlands",
"Biometric scan at IND desk after arrival",
],
"timeline": [
("University submits MVV application to IND", "8–10 weeks before start"),
("MVV entry visa issued", "4–8 weeks"),
("Travel to Netherlands", "On MVV"),
("Report to IND + biometrics → Residence permit", "Within 3 days of arrival"),
],
"tips": [
"The university processes most of the visa on your behalf — cooperate quickly with their international office.",
"Highly Skilled Migrant (HSM) permit after graduation gives 1 year to find skilled work.",
"Dutch education is largely in English — one of Europe's most international systems.",
"Holland Scholarship covers €5,000 of first-year tuition for non-EU students.",
],
},
"Japan": {
"visa_type": "College Student Visa (留学ビザ)",
"fee_inr": "₹1,300 (~¥3,000)",
"sevis_fee": "N/A",
"processing_weeks": "2–3 months (Certificate of Eligibility: 1–3 months)",
"validity": "1–2 years (renewable)",
"work_rights": "28 hrs/week with activity permit",
"pr_path": "Work visa (5 yr) → Permanent Residence (10 yr, or 5 yr with JLPT N2)",
"embassy_link": "https://www.in.emb-japan.go.jp/itpr_en/visa.html",
"documents": [
"Certificate of Eligibility (CoE) – issued by IMMI Japan, applied by university",
"Admission letter from Japanese institution",
"JLPT N2 (for Japanese programs) or IELTS/TOEFL (English programs)",
"Financial proof (tuition + ¥120,000+/month living)",
"Passport",
"Personal history and academic records",
"MEXT scholarship certificate (if applicable)",
],
"timeline": [
("University applies for CoE on your behalf", "3–4 months before start"),
("CoE issued by Japan Immigration", "1–3 months processing"),
("Apply for visa at Japanese Embassy with CoE", "1–2 weeks"),
("Visa stamping", "3–5 days"),
("Travel", "Before course starts"),
],
"tips": [
"MEXT scholarship (full government funding) is the best route — apply via Japanese Embassy in India.",
"CoE is issued by your Japanese university — the process is handled on your behalf.",
"JLPT N2 is required for most Japanese-language programs but not for English-medium ones.",
"Work rights of 28 hrs/week allow students to support daily living expenses.",
],
},
"South Korea": {
"visa_type": "D-2 Student Visa",
"fee_inr": "₹7,500 (~$90)",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "Program duration",
"work_rights": "20 hrs/week during semester; unlimited during vacation",
"pr_path": "D-10 (job search 6 mo) → E-7 work visa → F-2 → Permanent Residence",
"embassy_link": "https://overseas.mofa.go.kr/in-en/index.do",
"documents": [
"Admission letter from Korean university",
"Financial proof (KRW 10 million+ or ~₹6.3L)",
"TOPIK score (Korean programs) or IELTS/TOEFL (English programs)",
"Passport",
"Academic transcripts",
"Health certificate",
],
"timeline": [
("Apply at Korean Embassy in India", "4–6 weeks before start"),
("Visa decision", "2–4 weeks"),
("Alien Registration at Immigration Office in Korea", "Within 90 days of arrival"),
],
"tips": [
"KAIST and POSTECH offer full-ride scholarships for international students.",
"Korean Government Scholarship (GKS/KGSP) covers tuition, living, airfare.",
"Korean is very useful — even basic TOPIK Level 1 helps daily life significantly.",
],
},
"Switzerland": {
"visa_type": "National Visa D (Student)",
"fee_inr": "₹7,000 (~CHF 88)",
"sevis_fee": "Blocked account: CHF 21,000/yr",
"processing_weeks": "6–10 weeks",
"validity": "Course duration (renewable)",
"work_rights": "15 hrs/week during semester",
"pr_path": "Work permit → Settlement Permit C (10 years residence)",
"embassy_link": "https://www.sem.admin.ch/sem/en/home.html",
"documents": [
"University admission letter",
"Proof of financial resources (CHF 21,000/yr in blocked account)",
"Health insurance (Swiss-approved)",
"Passport (valid 6+ months)",
"Motivation letter",
"Academic transcripts and certificates",
"Language proficiency (German/French/English depending on program)",
],
"timeline": [
("Receive admission letter", "After application"),
("Open blocked account + insurance", "6–8 weeks before"),
("Apply at Swiss Embassy", "8–10 weeks before start"),
("Visa interview", "During processing"),
("Register at cantonal migration office", "Within 14 days of arrival"),
],
"tips": [
"Swiss public universities charge very low tuition (CHF 500–2,000/semester) — but living costs are high.",
"ETH Zurich and EPFL are world top-10 and nearly free for tuition.",
"Blocked account requirement is strict — CHF 21,000 must be deposited.",
"Learn basic German or French depending on the canton — it greatly helps daily life.",
],
},
"China": {
"visa_type": "X1 Student Visa (>180 days) / X2 (<180 days)",
"fee_inr": "₹3,500 (~$42)",
"sevis_fee": "N/A",
"processing_weeks": "1–4 weeks",
"validity": "Course duration (renewable)",
"work_rights": "Part-time with university approval (limited)",
"pr_path": "Work permit → Permanent Residence (very competitive, 5+ years)",
"embassy_link": "https://www.visaforchina.cn",
"documents": [
"JW201/JW202 form (issued by university)",
"Admission Notice from Chinese university",
"Passport (valid 6+ months)",
"Foreigner Physical Examination Form",
"Passport-size photos",
"Financial proof",
"HSK certificate (for Chinese-taught programs)",
],
"timeline": [
("Receive Admission Notice + JW form", "After admission"),
("Medical examination at approved clinic", "Before application"),
("Apply at Chinese Embassy/Visa Center", "4–6 weeks before start"),
("Visa issued", "1–4 weeks"),
("Register at local PSB within 24 hrs of arrival", "Day of arrival"),
],
"tips": [
"CSC Scholarship covers everything — apply through the Chinese Embassy for fully funded programs.",
"Learn basic Mandarin — most daily life outside campus requires Chinese.",
"Registration at the local Public Security Bureau within 24 hours of arrival is mandatory.",
"Many top programs (Tsinghua, Peking) offer English-medium Masters courses.",
],
},
"Sweden": {
"visa_type": "Residence Permit for Studies",
"fee_inr": "₹12,000 (~SEK 1,500)",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks",
"validity": "Course duration",
"work_rights": "Unlimited (no restriction during studies)",
"pr_path": "Work permit (2 yr) → Permanent Residence (4 yr total)",
"embassy_link": "https://www.migrationsverket.se/English/Private-individuals/Studying-in-Sweden.html",
"documents": [
"University admission letter",
"Proof of tuition payment (first semester)",
"Proof of financial resources (SEK 9,450/month)",
"Valid passport",
"Health insurance (EU students) or covered by Swedish system",
],
"timeline": [
("Pay tuition fee (first installment)", "After admission"),
("Apply for residence permit online", "As early as possible"),
("Biometrics at Swedish Embassy", "During processing"),
("Permit decision", "4–8 weeks"),
("Collect residence permit card", "At Swedish Embassy"),
],
"tips": [
"Sweden allows unlimited work hours during studies — one of the most generous in Europe.",
"SI Scholarship covers full tuition + living — highly competitive but worth applying.",
"Swedish universities have strong English-medium programs (among the best in Europe).",
"After graduation, you get 12 months to find a job without a work permit.",
],
},
"Denmark": {
"visa_type": "Residence Permit (ST1)",
"fee_inr": "₹25,000 (~DKK 2,550)",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks",
"validity": "Course duration + 6 months",
"work_rights": "20 hrs/week; full-time Jun-Aug",
"pr_path": "Work permit → Permanent Residence (8 years, or 4 with Danish language)",
"embassy_link": "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Study",
"documents": [
"University admission letter",
"Proof of financial resources (DKK 6,397/month)",
"Valid passport",
"Health insurance",
"Passport photograph",
"Proof of accommodation",
],
"timeline": [
("Receive admission + pay tuition", "After admission"),
("Apply online via nyidanmark.dk", "As early as possible"),
("Biometrics at Danish Embassy/VFS", "During processing"),
("Residence permit decision", "4–8 weeks"),
("Arrive and register with CPR", "After arrival"),
],
"tips": [
"DTU and University of Copenhagen offer world-class research programs.",
"PhD positions in Denmark are paid employment (~DKK 28,000/month salary).",
"Danish language proficiency significantly helps PR pathway.",
"Living costs are high — budget DKK 7,000–9,000/month for essentials.",
],
},
"Hong Kong": {
"visa_type": "Student Visa / Entry Permit",
"fee_inr": "₹4,000 (~HKD 360)",
"sevis_fee": "N/A",
"processing_weeks": "4–6 weeks",
"validity": "Course duration",
"work_rights": "20 hrs/week during semester; unlimited during summer & holidays",
"pr_path": "IANG visa (2 yr post-study) → 7 years continuous residence → PR",
"embassy_link": "https://www.immd.gov.hk/eng/services/visas/study.html",
"documents": [
"University admission letter + visa label (from university)",
"Financial proof (HKD 100,000+/year)",
"Valid passport",
"ID document",
"Academic transcripts",
"Proof of accommodation",
],
"timeline": [
("University sponsors visa application", "After admission"),
("Immigration Dept processes", "4–6 weeks"),
("Visa label issued to university", "Collected before travel"),
("Arrive and register", "Before course start"),
],
"tips": [
"HKPFS (PhD Fellowship) provides HKD 27,600/month — among Asia best funded PhDs.",
"IANG visa allows 2 years post-study work with no job requirement.",
"7 years continuous residence leads to Permanent Residency.",
"HKU, HKUST, CUHK are regularly in Asia top 10 — strong global recognition.",
],
},
"Malaysia": {
"visa_type": "Student Pass (EMGS)",
"fee_inr": "₹5,000–10,000",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "Course duration",
"work_rights": "20 hrs/week during semester break only",
"pr_path": "Employment Pass → PR (after 5+ years, case-by-case)",
"embassy_link": "https://educationmalaysia.gov.my",
"documents": [
"University offer letter",
"EMGS application (processed by university)",
"Medical examination",
"Valid passport (18+ months validity)",
"Academic transcripts",
"Financial proof",
"Passport-size photos",
],
"timeline": [
("University submits EMGS application", "After enrollment"),
("Visa Approval Letter (VAL) issued", "2–4 weeks"),
("Single Entry Visa at Malaysian Embassy", "1–2 weeks"),
("Arrive and complete Student Pass", "Within 7 days of arrival"),
],
"tips": [
"Malaysia is one of the most affordable study destinations — living costs are MYR 1,000–1,500/month.",
"Many world-class branch campuses (Monash, Nottingham) at fraction of main campus cost.",
"English is widely spoken — most university programs are in English.",
"Part-time work is only allowed during semester breaks; plan finances accordingly.",
],
},
"Norway": {
"visa_type": "Student Residence Permit",
"fee_inr": "₹5,500 (~NOK 6,300)",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks",
"validity": "Course duration + 1 year job-search",
"work_rights": "20 hrs/week during semester; full-time during holidays",
"pr_path": "Job-search permit (1 yr) → Work permit → Permanent Residence (3 yr)",
"embassy_link": "https://www.udi.no/en/want-to-apply/studies/",
"documents": [
"University admission letter",
"Financial proof (NOK 137,907/yr in Norwegian bank)",
"Valid passport",
"Housing confirmation",
"Health insurance (covered for residents)",
"Tuition receipt (most public unis are free)",
],
"timeline": [
("Open Norwegian bank account + deposit funds", "After admission"),
("Apply online via UDI", "As early as possible"),
("Biometrics at VFS/Embassy", "During processing"),
("Permit decision", "4–8 weeks"),
("Arrive and register", "Before course start"),
],
"tips": [
"Norwegian public universities are tuition-free even for international students!",
"Living costs are very high — budget NOK 12,000+/month.",
"PhD positions are paid employment with competitive salaries.",
"After studies, 1-year job-search permit is available.",
],
},
"Finland": {
"visa_type": "Residence Permit for Studies (Type B)",
"fee_inr": "₹3,500 (~EUR 350)",
"sevis_fee": "N/A",
"processing_weeks": "4–6 weeks",
"validity": "Course duration + 1 year",
"work_rights": "Unlimited hours if related to studies; 25 hrs/week otherwise",
"pr_path": "Extended permit → Permanent Residence (4 yr continuous)",
"embassy_link": "https://migri.fi/en/studying-in-finland",
"documents": [
"University admission letter",
"Proof of financial resources (EUR 6,720/yr or EUR 560/month)",
"Valid passport",
"Health insurance",
"Tuition fee receipt (if applicable)",
],
"timeline": [
("Receive admission + pay tuition", "After admission"),
("Apply at Finnish Embassy or online (Enter Finland)", "6–8 weeks before"),
("Biometrics", "During processing"),
("Permit decision", "4–6 weeks"),
("Register at DVV after arrival", "Within 1 week"),
],
"tips": [
"Finland consistently ranks #1 in education quality — Aalto and Helsinki are world-class.",
"PhD students get paid (EUR 2,500–3,500/month) as university employees.",
"1-year post-study residence permit for job search after graduation.",
"Living costs are moderate for Nordics — EUR 700–1,000/month.",
],
},
"Austria": {
"visa_type": "Residence Permit – Student",
"fee_inr": "₹12,000 (~EUR 160)",
"sevis_fee": "N/A",
"processing_weeks": "6–12 weeks",
"validity": "1 year (renewable)",
"work_rights": "20 hrs/week",
"pr_path": "Red-White-Red Card → Permanent Residence (5 yr)",
"embassy_link": "https://www.migration.gv.at/en/types-of-immigration/students/",
"documents": [
"University admission letter",
"Proof of financial resources (EUR 1,180/month)",
"Health insurance",
"Proof of accommodation",
"Valid passport",
"Birth certificate (apostilled)",
"Criminal record certificate",
],
"timeline": [
("Receive admission letter", "After admission"),
("Apply at Austrian Embassy", "12 weeks before start"),
("Document verification", "During processing"),
("Permit issued", "6–12 weeks"),
("Register at MA35 (Vienna)", "Within 3 days of arrival"),
],
"tips": [
"Austrian public universities charge only EUR 363/semester for most students.",
"Vienna is consistently ranked #1 most liveable city globally.",
"German language (B1+) is needed for daily life; many Masters programs are in English.",
"Red-White-Red Card for graduates allows post-study work and PR pathway.",
],
},
"Belgium": {
"visa_type": "Type D Student Visa",
"fee_inr": "₹15,000 (~EUR 200)",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks",
"validity": "1 year (renewable)",
"work_rights": "20 hrs/week during term",
"pr_path": "Work permit → Permanent Residence (5 yr)",
"embassy_link": "https://dofi.ibz.be/en/themes/third-country-nationals/study",
"documents": [
"University admission letter",
"Proof of financial resources (EUR 7,272/yr)",
"Health insurance",
"Valid passport",
"Medical certificate",
"Criminal record certificate",
"Motivation letter",
],
"timeline": [
("Receive admission", "After admission"),
("Apply at Belgian Embassy", "6–8 weeks before"),
("Document legalization", "During processing"),
("Visa issued", "4–8 weeks"),
("Register at commune (municipality)", "Within 8 days of arrival"),
],
"tips": [
"KU Leuven is consistently ranked #1 in Belgium and top 50 globally.",
"Belgium has 3 regions (Flanders, Wallonia, Brussels) — tuition varies by region.",
"Flemish universities (KU Leuven, Ghent) often have lower fees for non-EU students.",
"Brussels is the EU capital — excellent networking opportunities for policy/business students.",
],
},
"Poland": {
"visa_type": "National Visa D (Student)",
"fee_inr": "₹6,500 (~EUR 80)",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "1 year (renewable)",
"work_rights": "Unlimited hours during studies (no permit needed)",
"pr_path": "Temporary Residence → Permanent Residence (5 yr, or 3 yr with Polish Karta)",
"embassy_link": "https://www.gov.pl/web/india/student-visa",
"documents": [
"University admission letter",
"Proof of financial resources (PLN 776/month)",
"Health insurance (travel + local)",
"Valid passport",
"Passport-size photos",
"Tuition fee receipt",
],
"timeline": [
("Receive admission letter", "After admission"),
("Apply at Polish Embassy/VFS", "4–6 weeks before"),
("Visa issued", "2–4 weeks"),
("Arrive and register residence", "Within 30 days"),
],
"tips": [
"Poland is one of Europe's most affordable study destinations (EUR 2,000–4,000/yr tuition).",
"Unlimited work rights during studies — extremely student-friendly.",
"Many English-taught programs available at all major universities.",
"Living costs are EUR 400–600/month — significantly cheaper than Western Europe.",
],
},
"Portugal": {
"visa_type": "Residence Visa for Study (D4)",
"fee_inr": "₹7,500 (~EUR 90)",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks",
"validity": "Course duration",
"work_rights": "Part-time allowed",
"pr_path": "Temporary Residence → Permanent Residence (5 yr) → Citizenship (5 yr)",
"embassy_link": "https://www.sef.pt/en/pages/conteudo-detalhe.aspx?nID=21",
"documents": [
"University admission letter",
"Proof of financial resources (EUR 760/month)",
"Health insurance",
"Valid passport",
"Criminal record certificate",
"Proof of accommodation",
],
"timeline": [
("Receive admission", "After admission"),
("Apply at Portuguese Embassy", "6–8 weeks before"),
("Visa issued", "4–8 weeks"),
("Apply for Residence Permit at SEF", "Within 90 days of arrival"),
],
"tips": [
"Portugal offers one of the fastest EU citizenship paths (5 years).",
"Tuition is low (EUR 1,000–3,000/yr) at public universities.",
"Lisbon and Porto are increasingly popular tech hubs with growing job markets.",
"Portuguese language helps but many programs are in English.",
],
},
"Taiwan": {
"visa_type": "Resident Visa for Study",
"fee_inr": "₹5,500 (~$66)",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "Course duration",
"work_rights": "20 hrs/week with work permit",
"pr_path": "Work-based ARC → Permanent Residence (5 yr continuous)",
"embassy_link": "https://www.boca.gov.tw/mp-2.html",
"documents": [
"University admission letter",
"Financial proof (NTD 100,000+)",
"Valid passport",
"Health certificate",
"Academic transcripts",
"Study plan",
],
"timeline": [
("Receive admission", "After admission"),
("Apply at TECO office", "4–6 weeks before"),
("Visa issued", "2–4 weeks"),
("Arrive and apply for ARC", "Within 15 days"),
],
"tips": [
"Taiwan Scholarship covers tuition + NTD 15,000–20,000/month — excellent value.",
"NTU is ranked top 70 globally — strong for engineering and technology.",
"Living costs are very affordable (NTD 8,000–12,000/month for basics).",
"Mandarin Chinese courses are widely available and often free for scholarship students.",
],
},
"Russia": {
"visa_type": "Student Visa (учебная виза)",
"fee_inr": "₹4,000 (~$48)",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "Course duration (renewable)",
"work_rights": "Limited; permitted during holidays or with work permit",
"pr_path": "Temporary Residence Permit → Permanent Residence (3 yr) → Citizenship",
"embassy_link": "https://india.mid.ru/en/consular-services/visa/",
"documents": [
"University invitation letter (from Russian university)",
"Valid passport (18+ months validity)",
"HIV test certificate",
"Medical insurance",
"Passport-size photos",
"Application form",
"Financial proof",
],
"timeline": [
("Receive university invitation", "6–8 weeks before"),
("Apply at Russian Embassy/VFS", "4–6 weeks before start"),
("Visa issued", "2–4 weeks"),
("Arrive and register", "Within 7 days of arrival"),
],
"tips": [
"Russian Government Scholarship covers full tuition + stipend for international students.",
"Moscow State University and SPbU are among the world's oldest and most prestigious.",
"Living costs are very low — RUB 15,000–25,000/month ($150–250).",
"Learning basic Russian is essential — daily life outside major cities requires it.",
    ],
    },
    "Czech Republic": {
"visa_type": "Long-term Visa for Study (Type D)",
"fee_inr": "₹8,500 (~EUR 95)",
"sevis_fee": "N/A",
"processing_weeks": "8–12 weeks",
"validity": "1 year (renewable)",
"work_rights": "30 days/year; unlimited if university is accredited",
"pr_path": "Employee Card → Permanent Residence (5 yr)",
"embassy_link": "https://www.mzv.cz/newdelhi/en/ko/visas/long_term_visa_for_the_purpose_of_study.html",
"documents": [
"University acceptance document",
"Proof of financial resources (CZK 100,000+/yr)",
"Proof of accommodation",
"Valid passport",
"Criminal record certificate",
"Health insurance",
],
"timeline": [
("Receive acceptance document", "After admission"),
("Apply at Czech Embassy", "12+ weeks before start"),
("Visa interview", "During processing"),
("Visa decision", "8–12 weeks"),
("Register at Foreign Police", "Within 3 days of arrival"),
],
"tips": [
"Czech public universities offer FREE tuition if you study in the Czech language!",
"English-medium programs are also very affordable (EUR 2,000–5,000/yr).",
"Prague is a top-ranked student city with a very low cost of living.",
"Start the visa process early as processing can take full 3 months.",
],
},
"Mexico": {
"visa_type": "Student Visa (Residente Temporal Estudiante)",
"fee_inr": "₹4,200 (~$51)",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "1 year (renewable)",
"work_rights": "Limited (requires specific authorization)",
"pr_path": "Work visa → Permanent Residence (4–5 years)",
"embassy_link": "https://embamex.sre.gob.mx/india/index.php/en/",
"documents": [
"Acceptance letter from Mexican institution",
"Proof of economic solvency ($600+/month)",
"Valid passport",
"Visa application form",
"Passport-size photos",
],
"timeline": [
("Receive acceptance letter", "After admission"),
("Apply at Mexican Embassy", "4–6 weeks before start"),
("Visa interview", "Often required"),
("Visa label issued", "2–4 weeks"),
("Exchange visa for Resident Card", "Within 30 days of arrival"),
],
"tips": [
"Mexico has world-class institutions like UNAM and Tecnológico de Monterrey.",
"Spanish is essential for daily life, but many grad programs are in English.",
"Tuition is generally low, and cost of living is very affordable for Indians.",
"Exchange the visa label for a proper Resident Card at 'Instituto Nacional de Migración' immediately.",
],
},
"Chile": {
"visa_type": "Student Resident Visa (Visa de Residente Estudiante)",
"fee_inr": "₹5,000–8,000",
"sevis_fee": "N/A",
"processing_weeks": "4–8 weeks",
"validity": "1 year (renewable)",
"work_rights": "Only for mandatory internships or with special permit",
"pr_path": "Work visa → Permanent Residence (5+ years)",
"embassy_link": "https://chile.gob.cl/india/en/",
"documents": [
"Certificate of enrollment from Chilean university",
"Proof of financial support",
"Criminal record certificate",
"Health certificate",
"Valid passport",
"Police clearance (PCC)",
],
"timeline": [
("Receive enrollment certificate", "After admission"),
("Apply online via SAC Ciudadano", "6–8 weeks before"),
("Visa Approval", "4–8 weeks"),
("Register with PDI (Police)", "Within 30 days of arrival"),
],
"tips": [
"Chile is the most stable and prosperous economy in South America.",
"Pontificia Universidad Católica and UChile are top-ranked globally.",
"Scholarships from AGCI Chile are available for international students.",
"Amazing landscape — from Atacama desert to Patagonia — for student travel.",
],
},
"UAE": {
"visa_type": "Student Visa (Sponsored by University)",
"fee_inr": "₹25,000–45,000",
"sevis_fee": "N/A",
"processing_weeks": "2–4 weeks",
"validity": "1 year (renewable)",
"work_rights": "Allowed at approved employers/zones (e.g., Dubai)",
"pr_path": "Employment visa → Golden Visa (10 yr) for high-achievers",
"embassy_link": "https://u.ae/en/information-and-services/education/higher-education/student-visa",
"documents": [
"University admission letter",
"Medical fitness certificate",
"Visa sponsorship from institution",
"Passport copy",
"Passport photos",
"Tuition fee receipt",
],
"timeline": [
("University applies for visa on your behalf", "After tuition payment"),
("Entry permit issued", "1–2 weeks"),
("Medical test in UAE", "After arrival"),
("Emirates ID and Visa Stamping", "Within 2 weeks of arrival"),
],
"tips": [
"Dubai is a global educational hub with branch campuses from UK, USA, Australia.",
"Visa is usually sponsored by the university — check if fee is included in tuition.",
"Excellent job prospects and tax-free salaries after graduation.",
"Golden Visa available for outstanding students (GPA 3.8+).",
],
},
}

SOP_STRUCTURE = {
"Statement of Purpose (SOP)": {
"sections": [
("Opening Hook", "A compelling anecdote, observation, or question that reflects your passion for the field."),
("Academic Journey", "Relevant coursework, projects, thesis, CGPA, and how they led you here."),
("Professional Experience", "Internships, jobs, research — with specific outcomes and learnings."),
("Why This Program", "Specific courses, labs, faculty, and why THIS university over others."),
("Short & Long-term Goals", "Clear career trajectory: what you'll do in 2 years and 10 years."),
("Closing", "Reinforce fit and express enthusiasm authentically."),
],
"word_limit": "800–1,000 words",
"dos": [
"Be specific — name professors, lab groups, and courses",
"Quantify achievements (GPA, rank, impact numbers)",
"Show a clear narrative thread from past → present → future",
"Tailor each SOP uniquely per university",
"Use active voice and confident language",
],
"donts": [
"Don't start with 'Since childhood I dreamed...'",
"Don't list your resume — tell a story",
"Don't exceed word limit",
"Don't copy templates",
"Don't be vague about your goals",
],
"prompt_template": (
"Write a compelling Statement of Purpose for an Indian student applying to {program} at {university}. "
"Their background: {background}. "
"Structure the SOP with: (1) A compelling opening hook, (2) Academic journey and key projects, "
"(3) Professional experience and impact, (4) Why this specific program and university, "
"(5) Short and long-term career goals. "
"Word limit: 900 words. Avoid clichés. Be specific, confident, and authentic. "
"Do not use 'since childhood' openings."
),
},
"Letter of Recommendation (LOR)": {
"sections": [
("Referee Introduction", "How long and in what capacity the referee knows the applicant."),
("Academic/Professional Performance", "Specific examples of excellence, ranking, standout moments."),
("Key Qualities", "3–4 qualities with concrete evidence (leadership, research aptitude, etc.)."),
("Comparison Statement", "How the applicant ranks among peers the referee has seen."),
("Strong Endorsement", "Unequivocal recommendation with confidence."),
("Contact Info", "Referee's willingness to be contacted for follow-up."),
],
"word_limit": "400–600 words",
"dos": [
"Write in the referee's voice, not the student's",
"Cite specific incidents and accomplishments",
"Quantify: 'top 5% among 300 students I have taught'",
"Use official letterhead and wet signature",
"Be enthusiastic — half-hearted LORs hurt",
],
"donts": [
"Don't be generic ('a good student who works hard')",
"Don't exceed 600 words",
"Don't submit without referee's direct review",
"Don't use first-person from the student's side",
],
"prompt_template": (
"Write a strong Letter of Recommendation for {applicant_name} applying to {program} at {university}. "
"Referee: {referee_name}, {referee_role} at {referee_institution}. "
"Key achievements to highlight: {background}. "
"Structure: Introduction of referee's relationship with applicant → specific academic/professional performance "
"→ 3 standout qualities with evidence → comparison with peers → strong endorsement. "
"Word limit: 500 words. Professional tone. Use third person for the student."
),
},
"Personal Statement": {
"sections": [
("Personal Motivation", "What drives you — a personal story that connects to the field."),
("Academic Foundation", "Key subjects, research, thesis, or capstone that shaped your thinking."),
("Extra-curricular Impact", "Leadership, community work, creative work — linked to growth."),
("Program Alignment", "Specific program features that match your goals."),
("Future Vision", "Who you want to become and what you want to contribute."),
],
"word_limit": "500–650 words (UK UCAS) or 650–1,000 words (others)",
"dos": [
"UK UCAS: very structured, 4,000 characters max",
"Show personal growth, not just achievements",
"Connect personal story to academic interest",
"Be authentic — admissions readers spot padding",
],
"donts": [
"Don't repeat your CV",
"Don't mention grades unless exceptionally strong",
"Don't exceed character/word limits",
],
"prompt_template": (
"Write a personal statement for an Indian student applying to {program} at {university}. "
"Personal background and motivation: {background}. "
"Structure: Personal story → academic foundation → extra-curricular impact → program fit → future vision. "
"Word limit: 600 words. Warm, reflective, yet professional tone."
),
},
"Research Proposal": {
"sections": [
("Research Title", "Clear, specific, academic title."),
("Abstract", "100-word summary of the research question and methodology."),
("Background & Literature", "What exists, what gap you're addressing, key references."),
("Research Questions", "2–3 precise, answerable research questions."),
("Methodology", "Approach, data sources, analysis methods."),
("Timeline", "Realistic 6–12 month or multi-year plan."),
("Expected Outcomes", "What you expect to find or contribute."),
],
"word_limit": "1,500–3,000 words",
"dos": [
"Cite at least 10 recent peer-reviewed papers",
"Be specific about methodology (quantitative/qualitative/mixed)",
"Align with your proposed supervisor's research",
"Show feasibility within the program duration",
],
"donts": [
"Don't propose topics outside the supervisor's expertise",
"Don't be vague about methods",
"Don't ignore existing literature",
],
"prompt_template": (
"Write a research proposal for a PhD application in {program} at {university}. "
"Research area and background: {background}. "
"Structure: Title → Abstract (150 words) → Background & Literature Review → Research Questions (3) "
"→ Methodology → Timeline → Expected Outcomes. "
"Academic tone. Cite at least 5 relevant recent papers. Word limit: 1,500 words."
),
},
}

