# exam_db.py - Comprehensive entrance exams database
INDIAN_EXAMS = [
 {"name":"JEE Main","full_name":"Joint Entrance Examination Main","domain":"Engineering","body":"NTA","fee":"₹650-1300","next_date":"Jan & Apr 2026","eligibility":"12th with PCM (75%+)","syllabus":"Physics, Chemistry, Mathematics","website":"https://jeemain.nta.nic.in","is_international":False},
 {"name":"JEE Advanced","full_name":"Joint Entrance Examination Advanced","domain":"Engineering","body":"IITs","fee":"₹2800","next_date":"Jun 2026","eligibility":"Top 2.5L JEE Main qualifiers","syllabus":"Advanced Physics, Chemistry, Mathematics","website":"https://jeeadv.ac.in","is_international":False},
 {"name":"NEET-UG","full_name":"National Eligibility cum Entrance Test","domain":"Medical","body":"NTA","fee":"₹1700","next_date":"May 2026","eligibility":"12th with PCB (50%+)","syllabus":"Physics, Chemistry, Biology","website":"https://neet.nta.nic.in","is_international":False},
 {"name":"GATE","full_name":"Graduate Aptitude Test in Engineering","domain":"Engineering","body":"IITs","fee":"₹1700","next_date":"Feb 2026","eligibility":"BE/B.Tech graduates","syllabus":"Engineering subjects + Aptitude","website":"https://gate2026.iisc.ac.in","is_international":False},
 {"name":"CAT","full_name":"Common Admission Test","domain":"Management","body":"IIMs","fee":"₹2400","next_date":"Nov 2026","eligibility":"Graduation (50%+)","syllabus":"VARC, DILR, Quant","website":"https://iimcat.ac.in","is_international":False},
 {"name":"CUET-UG","full_name":"Common University Entrance Test UG","domain":"All","body":"NTA","fee":"₹650","next_date":"May 2026","eligibility":"12th pass","syllabus":"Domain + General Test + Language","website":"https://cuet.samarth.ac.in","is_international":False},
 {"name":"CUET-PG","full_name":"Common University Entrance Test PG","domain":"All","body":"NTA","fee":"₹800","next_date":"Jun 2026","eligibility":"Graduation","syllabus":"Domain-specific subjects","website":"https://cuet.nta.nic.in","is_international":False},
 {"name":"XAT","full_name":"Xavier Aptitude Test","domain":"Management","body":"XLRI","fee":"₹2000","next_date":"Jan 2026","eligibility":"Graduation","syllabus":"Verbal, Decision Making, Quant, GK","website":"https://xatonline.in","is_international":False},
 {"name":"MAT","full_name":"Management Aptitude Test","domain":"Management","body":"AIMA","fee":"₹1950","next_date":"Every quarter","eligibility":"Graduation","syllabus":"Language, Math, Data, Intelligence, Indian GK","website":"https://mat.aima.in","is_international":False},
 {"name":"NMAT","full_name":"NMIMS Management Aptitude Test","domain":"Management","body":"NMIMS","fee":"₹2300","next_date":"Oct-Dec 2026","eligibility":"Graduation","syllabus":"Language, Quant, Logical Reasoning","website":"https://www.nmat.org","is_international":False},
 {"name":"CLAT","full_name":"Common Law Admission Test","domain":"Law","body":"NLU Consortium","fee":"₹4000","next_date":"Dec 2026","eligibility":"12th pass (45%+)","syllabus":"English, GK, Legal Reasoning, Quant, Logic","website":"https://consortiumofnlus.ac.in","is_international":False},
 {"name":"AILET","full_name":"All India Law Entrance Test","domain":"Law","body":"NLU Delhi","fee":"₹3500","next_date":"Jun 2026","eligibility":"12th pass","syllabus":"English, GK, Legal Aptitude, Reasoning, Maths","website":"https://nludelhi.ac.in","is_international":False},
 {"name":"NIFT","full_name":"NIFT Entrance Exam","domain":"Design","body":"NIFT","fee":"₹3000","next_date":"Feb 2026","eligibility":"12th pass","syllabus":"Creative Ability, GAT, Situation Test","website":"https://nift.ac.in","is_international":False},
 {"name":"NID DAT","full_name":"NID Design Aptitude Test","domain":"Design","body":"NID","fee":"₹3000","next_date":"Jan 2026","eligibility":"12th pass","syllabus":"Design aptitude, Studio test","website":"https://admissions.nid.edu","is_international":False},
 {"name":"UGC NET","full_name":"University Grants Commission NET","domain":"All","body":"NTA","fee":"₹1100","next_date":"Jun & Dec 2026","eligibility":"PG degree (55%+)","syllabus":"Teaching aptitude + Subject paper","website":"https://ugcnet.nta.nic.in","is_international":False},
 {"name":"BITSAT","full_name":"BITS Admission Test","domain":"Engineering","body":"BITS Pilani","fee":"₹3400","next_date":"May 2026","eligibility":"12th with PCM (75%+)","syllabus":"Physics, Chemistry, Maths, English, Logic","website":"https://www.bitsadmission.com","is_international":False},
 {"name":"VITEEE","full_name":"VIT Engineering Entrance Exam","domain":"Engineering","body":"VIT","fee":"₹1350","next_date":"Apr 2026","eligibility":"12th with PCM (60%+)","syllabus":"Maths/Bio, Physics, Chemistry, English, Aptitude","website":"https://viteee.vit.ac.in","is_international":False},
 {"name":"SRMJEEE","full_name":"SRM Joint Engineering Entrance Exam","domain":"Engineering","body":"SRM","fee":"₹1100","next_date":"Apr 2026","eligibility":"12th with PCM","syllabus":"Physics, Chemistry, Maths/Biology, English, Aptitude","website":"https://www.srmist.edu.in","is_international":False},
]

INTERNATIONAL_EXAMS = [
 {"name":"GRE","full_name":"Graduate Record Examination","domain":"All","body":"ETS","fee":"$220 (~₹18,000)","next_date":"Year-round","eligibility":"Any graduate","syllabus":"Verbal Reasoning, Quantitative, Analytical Writing","website":"https://www.ets.org/gre","is_international":True,"accepted_in":"USA, Canada, UK, Europe, Australia"},
 {"name":"GMAT","full_name":"Graduate Management Admission Test","domain":"Management","body":"GMAC","fee":"$275 (~₹23,000)","next_date":"Year-round","eligibility":"Any graduate","syllabus":"Quantitative, Verbal, Integrated Reasoning, AWA","website":"https://www.mba.com/gmat","is_international":True,"accepted_in":"Worldwide MBA programs"},
 {"name":"TOEFL iBT","full_name":"Test of English as a Foreign Language","domain":"Language","body":"ETS","fee":"$200 (~₹16,500)","next_date":"Year-round","eligibility":"Non-native English speakers","syllabus":"Reading, Listening, Speaking, Writing","website":"https://www.ets.org/toefl","is_international":True,"accepted_in":"USA, Canada, Australia, UK, Europe"},
 {"name":"IELTS","full_name":"International English Language Testing System","domain":"Language","body":"British Council/IDP","fee":"₹16,250","next_date":"Multiple dates monthly","eligibility":"Non-native English speakers","syllabus":"Listening, Reading, Writing, Speaking","website":"https://www.ielts.org","is_international":True,"accepted_in":"UK, Australia, Canada, NZ, Europe, USA"},
 {"name":"SAT","full_name":"Scholastic Assessment Test","domain":"All","body":"College Board","fee":"$60 (~₹5,000)","next_date":"Mar, May, Jun, Aug, Oct, Nov, Dec","eligibility":"High school students","syllabus":"Reading & Writing, Mathematics","website":"https://satsuite.collegeboard.org","is_international":True,"accepted_in":"USA, Canada and worldwide UG programs"},
 {"name":"ACT","full_name":"American College Testing","domain":"All","body":"ACT Inc.","fee":"$68 (~₹5,600)","next_date":"Feb, Apr, Jun, Jul, Sep, Oct, Dec","eligibility":"High school students","syllabus":"English, Math, Reading, Science, Writing (optional)","website":"https://www.act.org","is_international":True,"accepted_in":"USA, Canada, and select international universities"},
 {"name":"PTE Academic","full_name":"Pearson Test of English Academic","domain":"Language","body":"Pearson","fee":"₹15,900","next_date":"Year-round","eligibility":"Non-native English speakers","syllabus":"Speaking & Writing, Reading, Listening","website":"https://www.pearsonpte.com","is_international":True,"accepted_in":"Australia, NZ, UK, Canada, USA"},
 {"name":"Duolingo English Test","full_name":"Duolingo English Test","domain":"Language","body":"Duolingo","fee":"$59 (~₹4,900)","next_date":"On-demand (online)","eligibility":"Anyone","syllabus":"Literacy, Conversation, Comprehension, Production","website":"https://englishtest.duolingo.com","is_international":True,"accepted_in":"4000+ universities worldwide"},
 {"name":"MCAT","full_name":"Medical College Admission Test","domain":"Medical","body":"AAMC","fee":"$330 (~₹27,000)","next_date":"Jan-Sep","eligibility":"Pre-med students","syllabus":"Bio, Chem, Physics, Psychology, Critical Analysis","website":"https://www.aamc.org/mcat","is_international":True,"accepted_in":"USA, Canada medical schools"},
 {"name":"LSAT","full_name":"Law School Admission Test","domain":"Law","body":"LSAC","fee":"$200 (~₹16,500)","next_date":"Multiple dates yearly","eligibility":"Law school applicants","syllabus":"Logical Reasoning, Analytical Reasoning, Reading","website":"https://www.lsac.org","is_international":True,"accepted_in":"USA, Canada, Australia law schools"},
 {"name":"TestDaF","full_name":"Test Deutsch als Fremdsprache","domain":"Language","body":"TestDaF Institut","fee":"€195 (~₹17,700)","next_date":"6 times/year","eligibility":"Students applying to German universities","syllabus":"Reading, Listening, Writing, Speaking (German)","website":"https://www.testdaf.de","is_international":True,"accepted_in":"All German universities"},
 {"name":"JLPT","full_name":"Japanese Language Proficiency Test","domain":"Language","body":"Japan Foundation","fee":"₹1,500","next_date":"Jul & Dec","eligibility":"Japanese language learners","syllabus":"Vocabulary, Grammar, Reading, Listening","website":"https://www.jlpt.jp","is_international":True,"accepted_in":"Japanese universities and employers"},
 {"name":"DELF/DALF","full_name":"Diplôme d'Études en Langue Française","domain":"Language","body":"France Education International","fee":"€150-300","next_date":"Multiple sessions","eligibility":"French language learners","syllabus":"Comprehension, Expression (oral & written)","website":"https://www.france-education-international.fr","is_international":True,"accepted_in":"French universities"},
 {"name":"TOPIK","full_name":"Test of Proficiency in Korean","domain":"Language","body":"NIIED","fee":"$40 (~₹3,300)","next_date":"Apr, Jul, Oct","eligibility":"Korean language learners","syllabus":"Listening, Reading, Writing","website":"https://www.topik.go.kr","is_international":True,"accepted_in":"Korean universities"},
]
ENTRANCE_EXAMS = [
    {
        "name": "JEE Advanced", "full_name": "Joint Entrance Exam – Advanced",
        "domain": "Engineering", "body": "IITs Joint Admission Board",
        "fee": "₹2,800", "next_date": "May 18, 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["All IITs", "IISc (some programs)"],
        "register_link": "https://jeeadv.ac.in", "info_link": "https://jeeadv.ac.in/about.html",
    },
    {
        "name": "JEE Main", "full_name": "Joint Entrance Exam – Main",
        "domain": "Engineering", "body": "National Testing Agency (NTA)",
        "fee": "₹1,000", "next_date": "Jan–Apr 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["NITs", "IIITs", "GFTIs", "State Engg Colleges"],
        "register_link": "https://jeemain.nta.nic.in", "info_link": "https://jeemain.nta.nic.in",
    },
    {
        "name": "GATE", "full_name": "Graduate Aptitude Test in Engineering",
        "domain": "Engineering", "body": "IITs / IISc",
        "fee": "₹1,800", "next_date": "Feb 7–15, 2026", "mode": "Online (CBT)",
        "validity": "3 years", "accepted_by": ["IITs", "NITs", "IISc", "ONGC", "BHEL", "PSUs"],
        "register_link": "https://gate2026.iitr.ac.in", "info_link": "https://gate.iitk.ac.in",
    },
    {
        "name": "CAT", "full_name": "Common Admission Test",
        "domain": "Management", "body": "Indian Institutes of Management (IIMs)",
        "fee": "₹2,400", "next_date": "Nov 23, 2025", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["All IIMs", "SPJIMR", "MDI", "IMT", "FMS Delhi", "NITIE"],
        "register_link": "https://iimcat.ac.in", "info_link": "https://iimcat.ac.in",
    },
    {
        "name": "NEET UG", "full_name": "National Eligibility cum Entrance Test (UG)",
        "domain": "Medical & Health", "body": "National Testing Agency (NTA)",
        "fee": "₹1,700", "next_date": "May 4, 2026", "mode": "Offline (OMR)",
        "validity": "Lifetime", "accepted_by": ["AIIMS", "All MBBS/BDS Colleges in India"],
        "register_link": "https://neet.nta.nic.in", "info_link": "https://neet.nta.nic.in",
    },
    {
        "name": "NEET PG", "full_name": "National Eligibility cum Entrance Test (PG)",
        "domain": "Medical & Health", "body": "National Board of Examinations",
        "fee": "₹4,250", "next_date": "Jun 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["All MD/MS/Diploma Medical Colleges"],
        "register_link": "https://nbe.edu.in", "info_link": "https://nbe.edu.in",
    },
    {
        "name": "CLAT", "full_name": "Common Law Admission Test",
        "domain": "Law", "body": "Consortium of NLUs",
        "fee": "₹4,000", "next_date": "Dec 1, 2025", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["All NLUs", "SYMBIOSIS LAW", "Jindal Law"],
        "register_link": "https://consortiumofnlus.ac.in", "info_link": "https://consortiumofnlus.ac.in",
    },
    {
        "name": "XAT", "full_name": "Xavier Aptitude Test",
        "domain": "Management", "body": "XLRI Jamshedpur",
        "fee": "₹2,200", "next_date": "Jan 5, 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["XLRI", "XIMB", "GIM", "IMT", "TAPMI", "150+ institutes"],
        "register_link": "https://xatonline.in", "info_link": "https://xatonline.in",
    },
    {
        "name": "SNAP", "full_name": "Symbiosis National Aptitude Test",
        "domain": "Management", "body": "Symbiosis International University",
        "fee": "₹1,950", "next_date": "Dec–Jan 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["SIBM Pune", "SCMHRD", "SIIB", "15+ SIU institutes"],
        "register_link": "https://www.snaptest.org", "info_link": "https://www.snaptest.org",
    },
    {
        "name": "NMAT", "full_name": "NMIMS Management Aptitude Test",
        "domain": "Management", "body": "GMAC / NMIMS",
        "fee": "₹2,400", "next_date": "Oct–Dec 2025", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["NMIMS Mumbai", "SBM NMIMS", "SPJIMR", "ISB"],
        "register_link": "https://www.nmat.org", "info_link": "https://www.nmat.org",
    },
    {
        "name": "BITSAT", "full_name": "BITS Admission Test",
        "domain": "Engineering", "body": "BITS Pilani",
        "fee": "₹3,400", "next_date": "May–Jun 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["BITS Pilani", "BITS Goa", "BITS Hyderabad"],
        "register_link": "https://www.bitsadmission.com", "info_link": "https://www.bitsadmission.com",
    },
    {
        "name": "JAM", "full_name": "Joint Admission test to M.Sc.",
        "domain": "Sciences", "body": "IITs",
        "fee": "₹1,800", "next_date": "Feb 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["IITs (M.Sc.)", "IISc", "NITs (M.Sc.)"],
        "register_link": "https://jam.iitg.ac.in", "info_link": "https://jam.iitg.ac.in",
    },
    {
        "name": "AILET", "full_name": "All India Law Entrance Test",
        "domain": "Law", "body": "NLU Delhi",
        "fee": "₹3,000", "next_date": "Dec 2025", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["NLU Delhi exclusively"],
        "register_link": "https://nludelhi.ac.in", "info_link": "https://nludelhi.ac.in",
    },
    {
        "name": "CMAT", "full_name": "Common Management Admission Test",
        "domain": "Management", "body": "NTA",
        "fee": "₹2,000", "next_date": "Mar 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["AICTE-approved B-schools", "JBIMS", "KJ Somaiya"],
        "register_link": "https://cmat.nta.nic.in", "info_link": "https://cmat.nta.nic.in",
    },
    {
        "name": "NID DAT", "full_name": "National Institute of Design – Design Aptitude Test",
        "domain": "Design & Architecture", "body": "NID Ahmedabad",
        "fee": "₹3,000", "next_date": "Jan 2026", "mode": "Offline",
        "validity": "1 year", "accepted_by": ["All NIDs", "CEPT", "SID IIT Bombay"],
        "register_link": "https://admissions.nid.edu", "info_link": "https://nid.edu",
    },
    {
        "name": "NATA", "full_name": "National Aptitude Test in Architecture",
        "domain": "Design & Architecture", "body": "Council of Architecture",
        "fee": "₹2,000", "next_date": "Apr–Jun 2026", "mode": "Online + Offline",
        "validity": "1 year", "accepted_by": ["All B.Arch colleges in India"],
        "register_link": "https://www.nata.in", "info_link": "https://www.nata.in",
    },
    {
        "name": "TISSNET", "full_name": "Tata Institute of Social Sciences – NET",
        "domain": "Social Sciences", "body": "TISS Mumbai",
        "fee": "₹1,030", "next_date": "Jan 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["TISS Mumbai", "TISS Hyderabad", "TISS Tuljapur"],
        "register_link": "https://tiss.edu/admissions", "info_link": "https://tiss.edu",
    },
    {
        "name": "CUCET", "full_name": "Central Universities Common Entrance Test",
        "domain": "Arts & Humanities", "body": "NTA",
        "fee": "₹700", "next_date": "May–Jun 2026", "mode": "Online (CBT)",
        "validity": "1 year", "accepted_by": ["All 45 Central Universities (UG)", "Delhi University", "BHU"],
        "register_link": "https://cucet.nta.nic.in", "info_link": "https://cucet.nta.nic.in",
    },
]

# ── Language / International Exams ────────────────────────────────────────────
LANGUAGE_EXAMS = [
    {
        "name": "IELTS", "full_name": "International English Language Testing System",
        "fee_inr": "17,000", "fee_usd": "205",
        "accepted_in": ["UK", "Australia", "Canada", "Germany", "Netherlands", "New Zealand", "Sweden", "Ireland"],
        "format": "Paper / Computer", "duration": "2 hrs 45 min", "validity": "2 Years",
        "centers_india": "150+", "score_info": "Band 0–9. Most universities require 6.5–7.5",
        "register_link": "https://www.ielts.org", "prep_link": "https://www.ielts.org/study-for-your-test",
        "center_link": "https://ielts.org/test-centre-search",
    },
    {
        "name": "TOEFL iBT", "full_name": "Test of English as a Foreign Language – Internet Based",
        "fee_inr": "18,500", "fee_usd": "222",
        "accepted_in": ["USA", "Canada", "UK", "Australia", "Germany", "Singapore", "Japan"],
        "format": "Online (at-home or test centre)", "duration": "2 hrs", "validity": "2 Years",
        "centers_india": "60+", "score_info": "Score 0–120. Top universities require 100+",
        "register_link": "https://www.ets.org/toefl", "prep_link": "https://www.ets.org/toefl/test-takers/ibt/prepare",
        "center_link": "https://www.ets.org/bin/getprogram.cgi?test=toefl",
    },
    {
        "name": "GRE", "full_name": "Graduate Record Examination",
        "fee_inr": "21,450", "fee_usd": "258",
        "accepted_in": ["USA", "Canada", "UK", "Australia", "Germany", "Singapore"],
        "format": "Online (at-home or test centre)", "duration": "1 hr 58 min", "validity": "5 Years",
        "centers_india": "40+", "score_info": "Verbal 130–170, Quant 130–170, AWA 0–6. Top unis expect 315+",
        "register_link": "https://www.ets.org/gre", "prep_link": "https://www.ets.org/gre/test-takers/general-test/prepare",
        "center_link": "https://www.ets.org/gre/test-takers/general-test/test-centers",
    },
    {
        "name": "GMAT Focus", "full_name": "Graduate Management Admission Test – Focus Edition",
        "fee_inr": "26,500", "fee_usd": "318",
        "accepted_in": ["USA", "UK", "Canada", "Australia", "Singapore", "UAE", "France", "Global"],
        "format": "Online (at-home or test centre)", "duration": "2 hrs 15 min", "validity": "5 Years",
        "centers_india": "30+", "score_info": "205–805. Top B-schools require 650+",
        "register_link": "https://www.mba.com/exams/gmat", "prep_link": "https://www.mba.com/exams/gmat/prepare",
        "center_link": "https://www.mba.com/exams/gmat/after-the-exam/test-center-policies",
    },
    {
        "name": "SAT", "full_name": "Scholastic Assessment Test",
        "fee_inr": "10,000", "fee_usd": "120",
        "accepted_in": ["USA", "Canada", "UK", "Singapore", "UAE", "Australia"],
        "format": "Digital (test centre)", "duration": "2 hrs 14 min", "validity": "Unlimited",
        "centers_india": "50+", "score_info": "400–1600. Top US universities expect 1400+",
        "register_link": "https://satsuite.collegeboard.org", "prep_link": "https://www.khanacademy.org/sat",
        "center_link": "https://satsuite.collegeboard.org/sat/registration/find-test-centers",
    },
    {
        "name": "PTE Academic", "full_name": "Pearson Test of English – Academic",
        "fee_inr": "15,900", "fee_usd": "190",
        "accepted_in": ["UK", "Australia", "Canada", "New Zealand", "Ireland", "Germany"],
        "format": "Computer (test centre)", "duration": "2 hrs", "validity": "2 Years",
        "centers_india": "60+", "score_info": "10–90. Australia visa requires 65+",
        "register_link": "https://www.pearsonpte.com", "prep_link": "https://www.pearsonpte.com/pte-academic/preparation",
        "center_link": "https://www.pearsonpte.com/pte-academic/test-centers",
    },
    {
        "name": "Duolingo English Test", "full_name": "Duolingo English Test",
        "fee_inr": "4,200", "fee_usd": "59",
        "accepted_in": ["USA", "Canada", "UK", "Germany", "Australia", "Netherlands"],
        "format": "Online (at-home)", "duration": "1 hr", "validity": "2 Years",
        "centers_india": "No centre needed", "score_info": "10–160. Many universities accept 105+",
        "register_link": "https://englishtest.duolingo.com", "prep_link": "https://englishtest.duolingo.com/guide",
        "center_link": "https://englishtest.duolingo.com",
    },
    {
        "name": "TestDaF", "full_name": "Test Deutsch als Fremdsprache",
        "fee_inr": "14,000", "fee_usd": "168",
        "accepted_in": ["Germany", "Austria", "Switzerland"],
        "format": "Paper / Computer", "duration": "3 hrs 10 min", "validity": "Unlimited",
        "centers_india": "15+", "score_info": "TDN 3–5 per section. TDN 4 needed for most German unis",
        "register_link": "https://www.testdaf.de", "prep_link": "https://www.testdaf.de/teilnehmer/vorbereitung",
        "center_link": "https://www.testdaf.de/pruefungszentren",
    },
    {
        "name": "JLPT N2", "full_name": "Japanese Language Proficiency Test N2",
        "fee_inr": "4,200", "fee_usd": "50",
        "accepted_in": ["Japan"],
        "format": "Paper", "duration": "2 hrs 5 min", "validity": "Unlimited",
        "centers_india": "8", "score_info": "0–180. N2 (score 90+) required for most Japanese unis",
        "register_link": "https://www.jlpt.jp", "prep_link": "https://www.jlpt.jp/e/samples/",
        "center_link": "https://www.jlpt.jp/e/application/domestic_index.html",
    },
    {
        "name": "MCAT", "full_name": "Medical College Admission Test",
        "fee_inr": "30,000", "fee_usd": "360",
        "accepted_in": ["USA", "Canada", "Australia"],
        "format": "Computer (test centre)", "duration": "7 hrs 33 min", "validity": "3 Years",
        "centers_india": "5", "score_info": "472–528. Most medical schools require 510+",
        "register_link": "https://students-residents.aamc.org/register-mcat", "prep_link": "https://students-residents.aamc.org/prepare-mcat",
        "center_link": "https://students-residents.aamc.org/find-test-center",
    },
    {
        "name": "LSAT", "full_name": "Law School Admission Test",
        "fee_inr": "20,000", "fee_usd": "240",
        "accepted_in": ["USA", "Canada", "Australia", "UK"],
        "format": "Online (at-home or test centre)", "duration": "2 hrs", "validity": "5 Years",
        "centers_india": "10", "score_info": "120–180. Top law schools require 170+",
        "register_link": "https://www.lsac.org", "prep_link": "https://www.lsac.org/lsat/lsat-prep",
        "center_link": "https://www.lsac.org/lsat/taking-lsat/test-centers",
    },
]

def get_all_exams():
    return ENTRANCE_EXAMS, LANGUAGE_EXAMS
