# uni_db.py - Real verified universities database with actual websites
def _u(n,c,ct,t,w,r=999,d="Engineering",f="15.0",rt=4.0):
    return {"name":n,"city":c,"country":ct,"type":t,"rank":r,"rating":rt,
            "domain":d,"degrees":["Bachelors","Masters","PhD"],"fees_inr":f,
            "admission_status":"Open","deadline":"Check website","highlights":["Top Research","Global Exposure","Modern Campus"],
            "website":w,"apply_link":w}

UNIVERSITIES_DB = {
"India": [
 _u("Indian Institute of Technology Bombay","Mumbai","India","Public","https://www.iitb.ac.in",1,"Engineering","2.5",4.9),
 _u("Indian Institute of Technology Delhi","New Delhi","India","Public","https://home.iitd.ac.in",2,"Engineering","2.5",4.8),
 _u("Indian Institute of Technology Madras","Chennai","India","Public","https://www.iitm.ac.in",3,"Engineering","2.5",4.8),
 _u("Indian Institute of Technology Kanpur","Kanpur","India","Public","https://www.iitk.ac.in",4,"Engineering","2.5",4.7),
 _u("Indian Institute of Technology Kharagpur","Kharagpur","India","Public","https://www.iitkgp.ac.in",5,"Engineering","2.5",4.7),
 _u("Indian Institute of Science","Bangalore","India","Public","https://www.iisc.ac.in",6,"Sciences","1.5",4.9),
 _u("Jawaharlal Nehru University","New Delhi","India","Public","https://www.jnu.ac.in"),
 _u("University of Delhi","New Delhi","India","Public","https://www.du.ac.in"),
 _u("Banaras Hindu University","Varanasi","India","Public","https://www.bhu.ac.in"),
 _u("Anna University","Chennai","India","Public","https://www.annauniv.edu"),
 _u("BITS Pilani","Pilani","India","Private","https://www.bits-pilani.ac.in"),
 _u("VIT Vellore","Vellore","India","Private","https://vit.ac.in"),
 _u("SRM Institute of Science and Technology","Chennai","India","Private","https://www.srmist.edu.in"),
 _u("Manipal Academy of Higher Education","Manipal","India","Private","https://manipal.edu"),
 _u("Amity University","Noida","India","Private","https://www.amity.edu"),
 _u("Symbiosis International University","Pune","India","Private","https://www.siu.edu.in"),
 _u("Lovely Professional University","Phagwara","India","Private","https://www.lpu.in"),
 _u("Christ University","Bangalore","India","Private","https://christuniversity.in"),
 _u("Ashoka University","Sonipat","India","Private","https://www.ashoka.edu.in"),
 _u("IIM Ahmedabad","Ahmedabad","India","Public","https://www.iima.ac.in"),
],
"USA": [
 _u("Massachusetts Institute of Technology","Cambridge","USA","Private","https://www.mit.edu",1,"Computer Science","45.0",5.0),
 _u("Stanford University","Stanford","USA","Private","https://www.stanford.edu",2,"Computer Science","48.0",5.0),
 _u("Harvard University","Cambridge","USA","Private","https://www.harvard.edu",3,"Management","52.0",5.0),
 _u("California Institute of Technology","Pasadena","USA","Private","https://www.caltech.edu",4,"Engineering","42.0",4.9),
 _u("University of California Berkeley","Berkeley","USA","Public","https://www.berkeley.edu"),
 _u("University of Michigan","Ann Arbor","USA","Public","https://umich.edu"),
 _u("University of Texas at Austin","Austin","USA","Public","https://www.utexas.edu"),
 _u("Georgia Institute of Technology","Atlanta","USA","Public","https://www.gatech.edu"),
 _u("University of Illinois Urbana-Champaign","Champaign","USA","Public","https://illinois.edu"),
 _u("University of Washington","Seattle","USA","Public","https://www.washington.edu"),
 _u("Carnegie Mellon University","Pittsburgh","USA","Private","https://www.cmu.edu"),
 _u("Columbia University","New York","USA","Private","https://www.columbia.edu"),
 _u("University of Pennsylvania","Philadelphia","USA","Private","https://www.upenn.edu"),
 _u("New York University","New York","USA","Private","https://www.nyu.edu"),
 _u("Purdue University","West Lafayette","USA","Public","https://www.purdue.edu"),
 _u("Arizona State University","Tempe","USA","Public","https://www.asu.edu",150,"Computer Science","28.0",4.2),
 _u("University of Florida","Gainesville","USA","Public","https://www.ufl.edu"),
 _u("Ohio State University","Columbus","USA","Public","https://www.osu.edu"),
 _u("Penn State University","State College","USA","Public","https://www.psu.edu"),
 _u("Boston University","Boston","USA","Private","https://www.bu.edu"),
],
 "UK": [
  _u("University of Oxford","Oxford","UK","Public","https://www.ox.ac.uk",1,"All","60.0",5.0),
  _u("University of Cambridge","Cambridge","UK","Public","https://www.cam.ac.uk",2,"All","60.0",5.0),
  _u("Imperial College London","London","UK","Public","https://www.imperial.ac.uk",3,"Engineering","45.0",4.9),
  _u("University College London","London","UK","Public","https://www.ucl.ac.uk",4,"All","40.0",4.8),
  _u("University of Edinburgh","Edinburgh","UK","Public","https://www.ed.ac.uk",5,"All","35.0",4.7),
  _u("University of Manchester","Manchester","UK","Public","https://www.manchester.ac.uk",6,"Engineering","32.0",4.6),
  _u("King's College London","London","UK","Public","https://www.kcl.ac.uk",7,"Medical","38.0",4.6),
  _u("London School of Economics","London","UK","Public","https://www.lse.ac.uk",8,"Management","42.0",4.7),
  _u("University of Warwick","Coventry","UK","Public","https://warwick.ac.uk",9,"Management","30.0",4.5),
  _u("University of Bristol","Bristol","UK","Public","https://www.bristol.ac.uk",10,"All","28.0",4.5),
  _u("Coventry University","Coventry","UK","Public","https://www.coventry.ac.uk",150,"All","18.0",4.0),
 ],
 "Canada": [
  _u("University of Toronto","Toronto","Canada","Public","https://www.utoronto.ca",1,"All","35.0",4.9),
  _u("University of British Columbia","Vancouver","Canada","Public","https://www.ubc.ca",2,"All","32.0",4.8),
  _u("McGill University","Montreal","Canada","Public","https://www.mcgill.ca",3,"All","30.0",4.8),
  _u("University of Waterloo","Waterloo","Canada","Public","https://uwaterloo.ca",4,"Engineering","28.0",4.7),
  _u("University of Alberta","Edmonton","Canada","Public","https://www.ualberta.ca",5,"All","22.0",4.5),
  _u("McMaster University","Hamilton","Canada","Public","https://www.mcmaster.ca",6,"Medical","25.0",4.5),
  _u("York University","Toronto","Canada","Public","https://www.yorku.ca",200,"Management","20.0",4.1),
 ],
 "Australia": [
  _u("University of Melbourne","Melbourne","Australia","Public","https://www.unimelb.edu.au",1,"All","28.0",4.8),
  _u("University of Sydney","Sydney","Australia","Public","https://www.sydney.edu.au",2,"All","27.0",4.7),
  _u("Australian National University","Canberra","Australia","Public","https://www.anu.edu.au",3,"All","26.0",4.7),
  _u("University of Queensland","Brisbane","Australia","Public","https://www.uq.edu.au",4,"All","25.0",4.6),
  _u("University of New South Wales","Sydney","Australia","Public","https://www.unsw.edu.au",5,"Engineering","26.0",4.6),
  _u("Monash University","Melbourne","Australia","Public","https://www.monash.edu",6,"All","24.0",4.5),
  _u("RMIT University","Melbourne","Australia","Public","https://www.rmit.edu.au",150,"Arts & Design","20.0",4.2),
  _u("Torrens University","Adelaide","Australia","Private","https://www.torrens.edu.au"),
 ],
"Germany": [
 _u("Technical University of Munich","Munich","Germany","Public","https://www.tum.de",37,"Engineering","0.5",4.9),
 _u("Ludwig Maximilian University","Munich","Germany","Public","https://www.lmu.de",50,"All","0.5",4.8),
 _u("Heidelberg University","Heidelberg","Germany","Public","https://www.uni-heidelberg.de",60,"Medical","0.5",4.8),
 _u("Humboldt University of Berlin","Berlin","Germany","Public","https://www.hu-berlin.de",100,"All","0.5",4.7),
 _u("Free University of Berlin","Berlin","Germany","Public","https://www.fu-berlin.de",110,"All","0.5",4.7),
 _u("RWTH Aachen University","Aachen","Germany","Public","https://www.rwth-aachen.de"),
 _u("University of Freiburg","Freiburg","Germany","Public","https://uni-freiburg.de"),
 _u("University of Gottingen","Gottingen","Germany","Public","https://www.uni-goettingen.de"),
 _u("Technical University of Berlin","Berlin","Germany","Public","https://www.tu.berlin"),
 _u("University of Stuttgart","Stuttgart","Germany","Public","https://www.uni-stuttgart.de"),
 _u("Karlsruhe Institute of Technology","Karlsruhe","Germany","Public","https://www.kit.edu"),
 _u("University of Hamburg","Hamburg","Germany","Public","https://www.uni-hamburg.de"),
],
"France": [
 _u("Sorbonne University","Paris","France","Public","https://www.sorbonne-universite.fr"),
 _u("Ecole Polytechnique","Palaiseau","France","Public","https://www.polytechnique.edu"),
 _u("Ecole Normale Superieure","Paris","France","Public","https://www.ens.psl.eu"),
 _u("University of Paris-Saclay","Gif-sur-Yvette","France","Public","https://www.universite-paris-saclay.fr"),
 _u("Sciences Po","Paris","France","Public","https://www.sciencespo.fr"),
 _u("INSEAD","Fontainebleau","France","Private","https://www.insead.edu"),
 _u("HEC Paris","Jouy-en-Josas","France","Private","https://www.hec.edu"),
 _u("University of Strasbourg","Strasbourg","France","Public","https://www.unistra.fr"),
 _u("Grenoble Alpes University","Grenoble","France","Public","https://www.univ-grenoble-alpes.fr"),
 _u("University of Lyon","Lyon","France","Public","https://www.universite-lyon.fr"),
],
"Singapore": [
 _u("National University of Singapore","Singapore","Singapore","Public","https://www.nus.edu.sg",8,"All","32.0",4.9),
 _u("Nanyang Technological University","Singapore","Singapore","Public","https://www.ntu.edu.sg",15,"Engineering","30.0",4.8),
 _u("Singapore Management University","Singapore","Singapore","Public","https://www.smu.edu.sg",100,"Management","35.0",4.7),
 _u("Singapore University of Technology and Design","Singapore","Singapore","Public","https://www.sutd.edu.sg",250,"Design & Tech","28.0",4.5),
 _u("Singapore Institute of Technology","Singapore","Singapore","Public","https://www.singaporetech.edu.sg"),
 _u("James Cook University Singapore","Singapore","Singapore","Private","https://www.jcu.edu.sg"),
 _u("INSEAD Asia Campus","Singapore","Singapore","Private","https://www.insead.edu/campuses/asia"),
],
"Netherlands": [
 _u("University of Amsterdam","Amsterdam","Netherlands","Public","https://www.uva.nl"),
 _u("Delft University of Technology","Delft","Netherlands","Public","https://www.tudelft.nl"),
 _u("Leiden University","Leiden","Netherlands","Public","https://www.universiteitleiden.nl"),
 _u("Utrecht University","Utrecht","Netherlands","Public","https://www.uu.nl"),
 _u("Erasmus University Rotterdam","Rotterdam","Netherlands","Public","https://www.eur.nl"),
 _u("Eindhoven University of Technology","Eindhoven","Netherlands","Public","https://www.tue.nl"),
 _u("University of Groningen","Groningen","Netherlands","Public","https://www.rug.nl"),
 _u("Wageningen University","Wageningen","Netherlands","Public","https://www.wur.nl"),
 _u("Vrije Universiteit Amsterdam","Amsterdam","Netherlands","Public","https://vu.nl"),
 _u("Maastricht University","Maastricht","Netherlands","Public","https://www.maastrichtuniversity.nl"),
],
"Japan": [
 _u("University of Tokyo","Tokyo","Japan","Public","https://www.u-tokyo.ac.jp"),
 _u("Kyoto University","Kyoto","Japan","Public","https://www.kyoto-u.ac.jp"),
 _u("Osaka University","Osaka","Japan","Public","https://www.osaka-u.ac.jp"),
 _u("Tokyo Institute of Technology","Tokyo","Japan","Public","https://www.titech.ac.jp"),
 _u("Tohoku University","Sendai","Japan","Public","https://www.tohoku.ac.jp"),
 _u("Nagoya University","Nagoya","Japan","Public","https://www.nagoya-u.ac.jp"),
 _u("Waseda University","Tokyo","Japan","Private","https://www.waseda.jp"),
 _u("Keio University","Tokyo","Japan","Private","https://www.keio.ac.jp"),
 _u("Hokkaido University","Sapporo","Japan","Public","https://www.hokudai.ac.jp"),
 _u("Kyushu University","Fukuoka","Japan","Public","https://www.kyushu-u.ac.jp"),
],
"Argentina": [
 _u("Universidad de Buenos Aires","Buenos Aires","Argentina","Public","https://www.uba.ar"),
 _u("Universidad Nacional de Cordoba","Cordoba","Argentina","Public","https://www.unc.edu.ar"),
 _u("Universidad Nacional de La Plata","La Plata","Argentina","Public","https://unlp.edu.ar"),
 _u("Universidad Austral","Buenos Aires","Argentina","Private","https://www.austral.edu.ar"),
 _u("Instituto Tecnologico de Buenos Aires","Buenos Aires","Argentina","Private","https://www.itba.edu.ar"),
 _u("Universidad de San Andres","Buenos Aires","Argentina","Private","https://udesa.edu.ar"),
 _u("Universidad Nacional de Rosario","Rosario","Argentina","Public","https://www.unr.edu.ar"),
 _u("Universidad Torcuato Di Tella","Buenos Aires","Argentina","Private","https://www.utdt.edu"),
],
"Brazil": [
 _u("University of Sao Paulo","Sao Paulo","Brazil","Public","https://www5.usp.br"),
 _u("University of Campinas","Campinas","Brazil","Public","https://www.unicamp.br"),
 _u("Federal University of Rio de Janeiro","Rio de Janeiro","Brazil","Public","https://ufrj.br"),
 _u("Federal University of Minas Gerais","Belo Horizonte","Brazil","Public","https://ufmg.br"),
 _u("Federal University of Rio Grande do Sul","Porto Alegre","Brazil","Public","https://www.ufrgs.br"),
 _u("Pontifical Catholic University of Rio","Rio de Janeiro","Brazil","Private","https://www.puc-rio.br"),
 _u("FGV - Fundacao Getulio Vargas","Sao Paulo","Brazil","Private","https://portal.fgv.br"),
],
"South Korea": [
 _u("Seoul National University","Seoul","South Korea","Public","https://www.snu.ac.kr"),
 _u("KAIST","Daejeon","South Korea","Public","https://www.kaist.ac.kr"),
 _u("Yonsei University","Seoul","South Korea","Private","https://www.yonsei.ac.kr"),
 _u("Korea University","Seoul","South Korea","Private","https://www.korea.ac.kr"),
 _u("POSTECH","Pohang","South Korea","Private","https://www.postech.ac.kr"),
 _u("Sungkyunkwan University","Seoul","South Korea","Private","https://www.skku.edu"),
 _u("Hanyang University","Seoul","South Korea","Private","https://www.hanyang.ac.kr"),
 _u("Korea Advanced Institute of Science","Daejeon","South Korea","Public","https://www.kaist.ac.kr"),
],
"Italy": [
 _u("University of Bologna","Bologna","Italy","Public","https://www.unibo.it"),
 _u("Sapienza University of Rome","Rome","Italy","Public","https://www.uniroma1.it"),
 _u("Politecnico di Milano","Milan","Italy","Public","https://www.polimi.it"),
 _u("University of Milan","Milan","Italy","Public","https://www.unimi.it"),
 _u("University of Padua","Padua","Italy","Public","https://www.unipd.it"),
 _u("University of Turin","Turin","Italy","Public","https://www.unito.it"),
 _u("Politecnico di Torino","Turin","Italy","Public","https://www.polito.it"),
 _u("Bocconi University","Milan","Italy","Private","https://www.unibocconi.eu"),
],
"Spain": [
 _u("University of Barcelona","Barcelona","Spain","Public","https://www.ub.edu"),
 _u("Autonomous University of Barcelona","Barcelona","Spain","Public","https://www.uab.cat"),
 _u("Complutense University of Madrid","Madrid","Spain","Public","https://www.ucm.es"),
 _u("Autonomous University of Madrid","Madrid","Spain","Public","https://www.uam.es"),
 _u("University of Valencia","Valencia","Spain","Public","https://www.uv.es"),
 _u("IE University","Madrid","Spain","Private","https://www.ie.edu"),
 _u("ESADE Business School","Barcelona","Spain","Private","https://www.esade.edu"),
 _u("University of Navarra","Pamplona","Spain","Private","https://www.unav.edu"),
],
"Ireland": [
 _u("Trinity College Dublin","Dublin","Ireland","Public","https://www.tcd.ie"),
 _u("University College Dublin","Dublin","Ireland","Public","https://www.ucd.ie"),
 _u("National University of Ireland Galway","Galway","Ireland","Public","https://www.nuigalway.ie"),
 _u("University College Cork","Cork","Ireland","Public","https://www.ucc.ie"),
 _u("Dublin City University","Dublin","Ireland","Public","https://www.dcu.ie"),
 _u("University of Limerick","Limerick","Ireland","Public","https://www.ul.ie"),
 _u("Maynooth University","Maynooth","Ireland","Public","https://www.maynoothuniversity.ie"),
 _u("Royal College of Surgeons Ireland","Dublin","Ireland","Private","https://www.rcsi.com"),
],
"New Zealand": [
 _u("University of Auckland","Auckland","New Zealand","Public","https://www.auckland.ac.nz"),
 _u("University of Otago","Dunedin","New Zealand","Public","https://www.otago.ac.nz"),
 _u("Victoria University of Wellington","Wellington","New Zealand","Public","https://www.wgtn.ac.nz"),
 _u("University of Canterbury","Christchurch","New Zealand","Public","https://www.canterbury.ac.nz"),
 _u("Massey University","Palmerston North","New Zealand","Public","https://www.massey.ac.nz"),
 _u("University of Waikato","Hamilton","New Zealand","Public","https://www.waikato.ac.nz"),
 _u("Lincoln University","Lincoln","New Zealand","Public","https://www.lincoln.ac.nz"),
],
"Switzerland": [
 _u("ETH Zurich","Zurich","Switzerland","Public","https://ethz.ch"),
 _u("EPFL","Lausanne","Switzerland","Public","https://www.epfl.ch"),
 _u("University of Zurich","Zurich","Switzerland","Public","https://www.uzh.ch"),
 _u("University of Basel","Basel","Switzerland","Public","https://www.unibas.ch"),
 _u("University of Bern","Bern","Switzerland","Public","https://www.unibe.ch"),
 _u("University of Geneva","Geneva","Switzerland","Public","https://www.unige.ch"),
 _u("University of Lausanne","Lausanne","Switzerland","Public","https://www.unil.ch"),
 _u("University of St. Gallen","St. Gallen","Switzerland","Public","https://www.unisg.ch"),
],
"China": [
 _u("Tsinghua University","Beijing","China","Public","https://www.tsinghua.edu.cn"),
 _u("Peking University","Beijing","China","Public","https://english.pku.edu.cn"),
 _u("Fudan University","Shanghai","China","Public","https://www.fudan.edu.cn"),
 _u("Zhejiang University","Hangzhou","China","Public","https://www.zju.edu.cn"),
 _u("Shanghai Jiao Tong University","Shanghai","China","Public","https://en.sjtu.edu.cn"),
 _u("Nanjing University","Nanjing","China","Public","https://www.nju.edu.cn"),
 _u("University of Science and Technology of China","Hefei","China","Public","https://en.ustc.edu.cn"),
 _u("Wuhan University","Wuhan","China","Public","https://en.whu.edu.cn"),
],
"Sweden": [
 _u("KTH Royal Institute of Technology","Stockholm","Sweden","Public","https://www.kth.se"),
 _u("Lund University","Lund","Sweden","Public","https://www.lunduniversity.lu.se"),
 _u("Uppsala University","Uppsala","Sweden","Public","https://www.uu.se"),
 _u("Stockholm University","Stockholm","Sweden","Public","https://www.su.se"),
 _u("Chalmers University of Technology","Gothenburg","Sweden","Public","https://www.chalmers.se"),
 _u("University of Gothenburg","Gothenburg","Sweden","Public","https://www.gu.se"),
 _u("Linkoping University","Linkoping","Sweden","Public","https://liu.se"),
],
"Denmark": [
 _u("University of Copenhagen","Copenhagen","Denmark","Public","https://www.ku.dk"),
 _u("Technical University of Denmark","Kongens Lyngby","Denmark","Public","https://www.dtu.dk"),
 _u("Aarhus University","Aarhus","Denmark","Public","https://www.au.dk"),
 _u("Aalborg University","Aalborg","Denmark","Public","https://www.aau.dk"),
 _u("University of Southern Denmark","Odense","Denmark","Public","https://www.sdu.dk"),
 _u("Copenhagen Business School","Copenhagen","Denmark","Public","https://www.cbs.dk"),
],
"Hong Kong": [
 _u("University of Hong Kong","Hong Kong","Hong Kong","Public","https://www.hku.hk"),
 _u("Hong Kong University of Science and Technology","Hong Kong","Hong Kong","Public","https://hkust.edu.hk"),
 _u("Chinese University of Hong Kong","Hong Kong","Hong Kong","Public","https://www.cuhk.edu.hk"),
 _u("Hong Kong Polytechnic University","Hong Kong","Hong Kong","Public","https://www.polyu.edu.hk"),
 _u("City University of Hong Kong","Hong Kong","Hong Kong","Public","https://www.cityu.edu.hk"),
 _u("Hong Kong Baptist University","Hong Kong","Hong Kong","Public","https://www.hkbu.edu.hk"),
],
"Malaysia": [
 _u("University of Malaya","Kuala Lumpur","Malaysia","Public","https://www.um.edu.my"),
 _u("Universiti Teknologi Malaysia","Johor Bahru","Malaysia","Public","https://www.utm.my"),
 _u("Universiti Sains Malaysia","Penang","Malaysia","Public","https://www.usm.my"),
 _u("Universiti Putra Malaysia","Serdang","Malaysia","Public","https://www.upm.edu.my"),
 _u("Monash University Malaysia","Subang Jaya","Malaysia","Private","https://www.monash.edu.my"),
 _u("Taylor's University","Subang Jaya","Malaysia","Private","https://university.taylors.edu.my"),
],
"Norway": [
 _u("University of Oslo","Oslo","Norway","Public","https://www.uio.no"),
 _u("Norwegian University of Science and Technology","Trondheim","Norway","Public","https://www.ntnu.edu"),
 _u("University of Bergen","Bergen","Norway","Public","https://www.uib.no"),
 _u("University of Tromso","Tromso","Norway","Public","https://en.uit.no"),
 _u("Norwegian School of Economics","Bergen","Norway","Public","https://www.nhh.no"),
],
"Finland": [
 _u("University of Helsinki","Helsinki","Finland","Public","https://www.helsinki.fi"),
 _u("Aalto University","Espoo","Finland","Public","https://www.aalto.fi"),
 _u("University of Turku","Turku","Finland","Public","https://www.utu.fi"),
 _u("Tampere University","Tampere","Finland","Public","https://www.tuni.fi"),
 _u("University of Oulu","Oulu","Finland","Public","https://www.oulu.fi"),
],
"Austria": [
 _u("University of Vienna","Vienna","Austria","Public","https://www.univie.ac.at"),
 _u("Vienna University of Technology","Vienna","Austria","Public","https://www.tuwien.at"),
 _u("University of Innsbruck","Innsbruck","Austria","Public","https://www.uibk.ac.at"),
 _u("University of Graz","Graz","Austria","Public","https://www.uni-graz.at"),
 _u("Graz University of Technology","Graz","Austria","Public","https://www.tugraz.at"),
 _u("WU Vienna University of Economics","Vienna","Austria","Public","https://www.wu.ac.at"),
],
"Belgium": [
 _u("KU Leuven","Leuven","Belgium","Public","https://www.kuleuven.be"),
 _u("Ghent University","Ghent","Belgium","Public","https://www.ugent.be"),
 _u("Universite Libre de Bruxelles","Brussels","Belgium","Public","https://www.ulb.be"),
 _u("Vrije Universiteit Brussel","Brussels","Belgium","Public","https://www.vub.be"),
 _u("University of Antwerp","Antwerp","Belgium","Public","https://www.uantwerpen.be"),
 _u("UCLouvain","Louvain-la-Neuve","Belgium","Public","https://uclouvain.be"),
],
"Poland": [
 _u("University of Warsaw","Warsaw","Poland","Public","https://www.uw.edu.pl"),
 _u("Jagiellonian University","Krakow","Poland","Public","https://www.uj.edu.pl"),
 _u("Warsaw University of Technology","Warsaw","Poland","Public","https://www.pw.edu.pl"),
 _u("AGH University of Science and Technology","Krakow","Poland","Public","https://www.agh.edu.pl"),
 _u("Adam Mickiewicz University","Poznan","Poland","Public","https://amu.edu.pl"),
],
"Portugal": [
 _u("University of Lisbon","Lisbon","Portugal","Public","https://www.ulisboa.pt"),
 _u("University of Porto","Porto","Portugal","Public","https://www.up.pt"),
 _u("University of Coimbra","Coimbra","Portugal","Public","https://www.uc.pt"),
 _u("NOVA University Lisbon","Lisbon","Portugal","Public","https://www.unl.pt"),
 _u("University of Aveiro","Aveiro","Portugal","Public","https://www.ua.pt"),
],
"Czech Republic": [
 _u("Charles University","Prague","Czech Republic","Public","https://cuni.cz"),
 _u("Czech Technical University in Prague","Prague","Czech Republic","Public","https://www.cvut.cz"),
 _u("Masaryk University","Brno","Czech Republic","Public","https://www.muni.cz"),
 _u("Brno University of Technology","Brno","Czech Republic","Public","https://www.vut.cz"),
],
"Mexico": [
 _u("UNAM","Mexico City","Mexico","Public","https://www.unam.mx"),
 _u("Tecnologico de Monterrey","Monterrey","Mexico","Private","https://tec.mx"),
 _u("Universidad Iberoamericana","Mexico City","Mexico","Private","https://ibero.mx"),
 _u("ITAM","Mexico City","Mexico","Private","https://www.itam.mx"),
 _u("Universidad Autonoma Metropolitana","Mexico City","Mexico","Public","https://www.uam.mx"),
],
"Chile": [
 _u("Pontificia Universidad Catolica de Chile","Santiago","Chile","Private","https://www.uc.cl"),
 _u("Universidad de Chile","Santiago","Chile","Public","https://www.uchile.cl"),
 _u("Universidad de Concepcion","Concepcion","Chile","Public","https://www.udec.cl"),
 _u("Universidad Adolfo Ibanez","Santiago","Chile","Private","https://www.uai.cl"),
],
"Taiwan": [
 _u("National Taiwan University","Taipei","Taiwan","Public","https://www.ntu.edu.tw"),
 _u("National Tsing Hua University","Hsinchu","Taiwan","Public","https://www.nthu.edu.tw"),
 _u("National Chiao Tung University","Hsinchu","Taiwan","Public","https://www.nycu.edu.tw"),
 _u("National Cheng Kung University","Tainan","Taiwan","Public","https://www.ncku.edu.tw"),
 _u("National Taiwan University of Science and Technology","Taipei","Taiwan","Public","https://www.ntust.edu.tw"),
],
"UAE": [
 _u("Khalifa University","Abu Dhabi","UAE","Public","https://www.ku.ac.ae"),
 _u("United Arab Emirates University","Al Ain","UAE","Public","https://www.uaeu.ac.ae"),
 _u("American University of Sharjah","Sharjah","UAE","Private","https://www.aus.edu"),
 _u("University of Sharjah","Sharjah","UAE","Private","https://www.sharjah.ac.ae"),
 _u("New York University Abu Dhabi","Abu Dhabi","UAE","Private","https://nyuad.nyu.edu"),
 _u("Heriot-Watt University Dubai","Dubai","UAE","Private","https://www.hw.ac.uk/dubai"),
],
"Russia": [
 _u("Lomonosov Moscow State University","Moscow","Russia","Public","https://www.msu.ru"),
 _u("Saint Petersburg State University","Saint Petersburg","Russia","Public","https://english.spbu.ru"),
 _u("Bauman Moscow State Technical University","Moscow","Russia","Public","https://bmstu.ru"),
 _u("ITMO University","Saint Petersburg","Russia","Public","https://en.itmo.ru"),
 _u("Novosibirsk State University","Novosibirsk","Russia","Public","https://english.nsu.ru"),
],
}

def get_country_universities(country="All"):
    """Get universities for a country. Returns instantly from hardcoded DB."""
    if country == "All":
        all_unis = []
        for unis in UNIVERSITIES_DB.values():
            all_unis.extend(unis)
        return all_unis
    if country == "Abroad":
        all_unis = []
        for c, unis in UNIVERSITIES_DB.items():
            if c != "India":
                all_unis.extend(unis)
        return all_unis
    # Try exact match first
    if country in UNIVERSITIES_DB:
        return list(UNIVERSITIES_DB[country])
    # Try case-insensitive
    for k, v in UNIVERSITIES_DB.items():
        if k.lower() == country.lower():
            return list(v)
    return []
